// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDATA.DBContext;

namespace ProyectoDATA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210316023832_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Seguridad.Traza", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("NombreAccion")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("NombrePC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("ObjetoAntesModificar")
                        .HasColumnType("json");

                    b.Property<string>("ObjetoCreado")
                        .HasColumnType("json");

                    b.Property<string>("ObjetoEliminado")
                        .HasColumnType("json");

                    b.Property<string>("ObjetoModificado")
                        .HasColumnType("json");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("Id_UNIQUE");

                    b.HasIndex("NombreAccion")
                        .HasDatabaseName("FK_NombreAccion_Trazas_idx");

                    b.ToTable("Trazas");
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0",
                            AccessFailedCount = 0,
                            Apellidos = "Administrador",
                            ConcurrencyStamp = "44c8c6e9-f046-4af2-92ba-eb91b232b110",
                            Email = "administrador@tienda.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Nombre = "Usuario",
                            NormalizedEmail = "ADMINISTRADOR@TIENDA.COM",
                            NormalizedUserName = "ADMINISTRADOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEAkXw5Al5CMhhZiQOvGxpO4d5hOXE4YdHbHv7NvP7wXhuwIPQkBLgjM+4zHCkBqaPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NLN3QCO657I7UVCHLVZ2AMKFMK37JCIY",
                            TwoFactorEnabled = false,
                            UserName = "administrador"
                        },
                        new
                        {
                            Id = "549889bf-fec3-4403-a536-133cd8cdeac5",
                            AccessFailedCount = 0,
                            Apellidos = "Vendedor",
                            ConcurrencyStamp = "44c8c6e9-f046-4af2-92ba-eb91b232b110",
                            Email = "vendedor@tienda.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Nombre = "Usuario",
                            NormalizedEmail = "VENDEDOR@TIENDA.COM",
                            NormalizedUserName = "VENDEDOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEAkXw5Al5CMhhZiQOvGxpO4d5hOXE4YdHbHv7NvP7wXhuwIPQkBLgjM+4zHCkBqaPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NLN3QCO657I7UVCHLVZ2AMKFMK37JCIY",
                            TwoFactorEnabled = false,
                            UserName = "vendedor"
                        },
                        new
                        {
                            Id = "787d0bc9-048c-4e9f-b6c3-df267442a3aa",
                            AccessFailedCount = 0,
                            Apellidos = "Cliente",
                            ConcurrencyStamp = "44c8c6e9-f046-4af2-92ba-eb91b232b110",
                            Email = "cliente@tienda.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Nombre = "Usuario",
                            NormalizedEmail = "CLIENTE@TIENDA.COM",
                            NormalizedUserName = "CLIENTE",
                            PasswordHash = "AQAAAAEAACcQAAAAEAkXw5Al5CMhhZiQOvGxpO4d5hOXE4YdHbHv7NvP7wXhuwIPQkBLgjM+4zHCkBqaPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NLN3QCO657I7UVCHLVZ2AMKFMK37JCIY",
                            TwoFactorEnabled = false,
                            UserName = "cliente"
                        });
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Tienda.Orden", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ProductoId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("Id_UNIQUE");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ordenes");

                    b.HasData(
                        new
                        {
                            Id = "4cd7a29e-1e21-4697-b3c9-b7f8ea30a72d",
                            Cantidad = 20,
                            Estado = 1,
                            Fecha = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = "6c875378-7bf3-4ca3-b056-bc360d65ac8c",
                            UsuarioId = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0"
                        },
                        new
                        {
                            Id = "40ea0e5d-c412-45f7-94f6-3e0051350f96",
                            Cantidad = 10,
                            Estado = 0,
                            Fecha = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = "1df535e8-9f12-4b9a-a780-f32a21c123a9",
                            UsuarioId = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0"
                        },
                        new
                        {
                            Id = "72690b9a-0afb-4b3c-98c8-26809816bd7d",
                            Cantidad = 5,
                            Estado = 0,
                            Fecha = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = "1df535e8-9f12-4b9a-a780-f32a21c123a9",
                            UsuarioId = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0"
                        },
                        new
                        {
                            Id = "f2f4a187-3f67-4eb3-8bc8-b1550bd9ffe8",
                            Cantidad = 2,
                            Estado = 2,
                            Fecha = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = "1df535e8-9f12-4b9a-a780-f32a21c123a9",
                            UsuarioId = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0"
                        },
                        new
                        {
                            Id = "0d4d759f-58f6-4dd2-a890-079f2ffef68c",
                            Cantidad = 20,
                            Estado = 1,
                            Fecha = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductoId = "6c875378-7bf3-4ca3-b056-bc360d65ac8c",
                            UsuarioId = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0"
                        });
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Tienda.Producto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Cantidad")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("Id_UNIQUE");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("Nombre_UNIQUE");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = "5d1a6250-4bdc-46c0-8fb7-b965dad45d79",
                            Cantidad = 220,
                            CreadoPor = "vendedor",
                            Descripcion = "MotherBoard",
                            FechaCreado = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Motherboard",
                            Precio = 20.989999999999998
                        },
                        new
                        {
                            Id = "4b5a5caa-8858-4faa-9e86-c5023d1119cd",
                            Cantidad = 614,
                            CreadoPor = "vendedor",
                            Descripcion = "Mouse",
                            FechaCreado = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Mouse",
                            Precio = 52.0
                        },
                        new
                        {
                            Id = "4a7b536f-7777-4af9-bec8-e9a9530d630d",
                            Cantidad = 20,
                            CreadoPor = "vendedor",
                            Descripcion = "Monitor",
                            FechaCreado = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Monitor",
                            Precio = 65.650000000000006
                        },
                        new
                        {
                            Id = "1df535e8-9f12-4b9a-a780-f32a21c123a9",
                            Cantidad = 220,
                            CreadoPor = "vendedor",
                            Descripcion = "RAM",
                            FechaCreado = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ram",
                            Precio = 20.0
                        },
                        new
                        {
                            Id = "6c875378-7bf3-4ca3-b056-bc360d65ac8c",
                            Cantidad = 220,
                            CreadoPor = "vendedor",
                            Descripcion = "KeyBoard",
                            FechaCreado = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Keyboard",
                            Precio = 10.99
                        });
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Seguridad.Rol", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("Rol");

                    b.HasData(
                        new
                        {
                            Id = "91e0f2a3-3a4c-46e4-83a6-94356cd46725",
                            ConcurrencyStamp = "dc0aeb28-2e47-483d-9a1a-1396f6aa374d",
                            Name = "Administrador",
                            Descripcion = "Administradores de la tienda"
                        },
                        new
                        {
                            Id = "f56dc294-76e6-4277-9685-b4ca524f61d8",
                            ConcurrencyStamp = "b6ef9fe3-415b-4688-9fec-64a46c0a20e9",
                            Name = "Vendedor",
                            Descripcion = "Vendedor de la tienda"
                        },
                        new
                        {
                            Id = "49efd009-ced5-4fb9-868d-cf365a34765f",
                            ConcurrencyStamp = "b1327f26-fce3-4e93-bc2a-8edd332bdc78",
                            Name = "Cliente",
                            Descripcion = "Cliente de la tienda"
                        });
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Seguridad.Rol_Usuarios", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasDiscriminator().HasValue("Rol_Usuarios");

                    b.HasData(
                        new
                        {
                            UserId = "f6a8c8eb-309c-4ca7-91e1-46aa0ff16bc0",
                            RoleId = "91e0f2a3-3a4c-46e4-83a6-94356cd46725"
                        },
                        new
                        {
                            UserId = "549889bf-fec3-4403-a536-133cd8cdeac5",
                            RoleId = "f56dc294-76e6-4277-9685-b4ca524f61d8"
                        },
                        new
                        {
                            UserId = "787d0bc9-048c-4e9f-b6c3-df267442a3aa",
                            RoleId = "49efd009-ced5-4fb9-868d-cf365a34765f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Tienda.Orden", b =>
                {
                    b.HasOne("ProyectoDATA.Entidades.Mod_Tienda.Producto", "Producto")
                        .WithMany("Ordenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", "Usuario")
                        .WithMany("Ordenes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Seguridad.Usuario", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("ProyectoDATA.Entidades.Mod_Tienda.Producto", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
